<?xml version="1.0"?>
<package format="3">
  <name>carma_bridge</name>
  <version>0.1.0</version>
  <description>Bridge between the carma library and ROS 2.</description>
  <maintainer email="none@example.invalid">Erick</maintainer>
  <license>Apache-2.0</license>

  <depend>rclpy</depend>
  <depend>sensor_msgs</depend>
  <depend>geometry_msgs</depend>
  <depend>nav_msgs</depend>
  <depend>std_srvs</depend>
  <depend>cv_bridge</depend>
  <depend>message_filters</depend>

  <export>
    <build_type>ament_python</build_type>
  </export>
</package>
