<?xml version="1.0"?>
<package format="3">
  <name>carma_sim</name>
  <version>0.1.0</version>
  <description>Gazebo Harmonic worlds and UGV description for CARMA.</description>
  <maintainer email="none@example.invalid">Erick</maintainer>
  <license>Apache-2.0</license>

  <depend>ros_gz_sim</depend>
  <depend>ros_gz_bridge</depend>

  <export>
    <build_type>ament_cmake</build_type>
  </export>
</package>
